#config/hydra/launcher/slurm.yaml

defaults:
  - submitit_slurm

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j

timeout_min: ${testing.timeout_min}
mem_gb: ${testing.mem_gb}
cpus_per_task: ${dataset.general_dataset_config.num_workers}


partition: orchid #standard
qos: orchid #short
account: orchid #iecdt

gres: gpu:1

exclude: gpuhost004,gpuhost009,gpuhost012,gpuhost007


#additional_parameters:

# https://help.jasmin.ac.uk/docs/batch-computing/how-to-submit-a-job/