name: unet

# single_run_configuration:
#   lr: 0.001
#   batch_size: 2048
#   activation: relu
#   optimizer: Adam
#   scheduler: None
  
single_run_configuration:
  lr: 7e-4 #1e-4
  batch_size: 2048
  optimizer: Adam
  scheduler: 
    name: step
    step_size: 3 # epochs
    gamma: 0.5