# output directory, generated dynamically on each run
run:
  dir: ${hydra:runtime.cwd}/logs/${project.project}/${project.task}/${project.name}_${project.timestamp}
sweep:
  dir: logs/${project.project}/${project.task}/${project.name}_${project.timestamp}
  subdir: ${multirun_dir_name}
job:
  chdir: True # change to the output directory on each run