mlp:
  multi_env: False
  early_stopping_patience: 200
  sweep_configuration:
    name: ${project.name}_process_${proc_seed}_mlp
    method: random
    metric:
      name: val/loss
      goal: minimize
    parameters:
      lr:
        distribution: log_uniform_values
        min: 1e-5
        max: 1e-1
      batch_size:
        values: [16, 32, 64, 128, 256, 512, 1024]
      hidden_dim:
        values: [1, 2, 8, 16, 32, 64, 128, 256]
      nhidden:
        values: [1, 2, 3, 4, 5, 6, 7, 8]

  single_run_configuration:
    lr: 0.001
    batch_size: 64
    hidden_dim: 32
    nhidden: 2