energy_distance_standard: # Standard (no or full testing)
  K_cross: 200000
  K_within: 200000
  batch_size: 20000
  num_permutations: 500

energy_distance_test: # Reduced testing settings
  K_cross: 384
  K_within: 384
  batch_size: 384
  num_permutations: 50