
# Used for the MetricWrapper for optimisations when running the metrics on large quantities of data
sample_size: ${testing.sample_size}
n_samples: ${testing.n_samples}
batch_size: ${testing.batch_size}

pca_components: 15