# Dress rehearsal: A more serious 'flush through' of system, but they should result in meaningful results, i.e loss curves and comparable metrics

test_name: dress_rehearsal

hydra:
  run:
    dir: ${hydra:runtime.cwd}/logs/${project.project}/${project.task}/testing/dress_rehearsal/${project.timestamp}
  sweep:
    dir: logs/${project.project}/${project.task}/testing/dress_rehearsal/${project.timestamp}

wandb_mode: online 
dataset: reduced
epochs: 10
plotting: True
timings: False
