# Dress rehearsal: A more serious 'flush through' of system, but still with reduced settings

test_name: dress_rehearsal

hydra:
  run:
    dir: ${hydra:runtime.cwd}/logs/${project.project}/${project.task}/testing/dress_rehearsal/${project.timestamp}
  sweep:
    dir: logs/${project.project}/${project.task}/testing/dress_rehearsal/${project.timestamp}

wandb_mode: online
dataset_testing_type: reduced
epochs: 3
plotting: True
time_analysis: False
num_workers: 4
timeout_min: 120
mem_gb: 32

# evaluate data group metric settings
sample_size: 1000
n_samples: 10
batch_size: False



# OBSOLETE
energy_distance:
  K_cross: ${evaluate.energy_distance_test.K_cross}
  K_within: ${evaluate.energy_distance_test.K_within}
  batch_size: ${evaluate.energy_distance_test.batch_size}
  num_permutations: ${evaluate.energy_distance_test.num_permutations}

