# Functional test: A proper run through of the full system, but perhaps not full training or sweeps, the purpose is to assess for bottle necks, functional performance and a basic understanding of behavior to finetune sweeps


hydra:
  run:
    dir: ${hydra:runtime.cwd}/logs/${project.project}/${project.task}/testing/functional_test/${project.timestamp}
  sweep:
    dir: logs/${project.project}/${project.task}/testing/functional_test/${project.timestamp}

wandb_mode: enabled 
dataset: full
epochs: ${epochs}
plotting: True
timings: True