# Functional test: A proper run through of the full system, but perhaps not full training or sweeps, the purpose is to assess for bottle necks, functional performance and a basic understanding of behavior to finetune sweeps

test_name: functional_test

hydra:
  run:
    dir: ${hydra:runtime.cwd}/logs/${project.project}/${project.task}/testing/functional_test/${project.timestamp}
  sweep:
    dir: logs/${project.project}/${project.task}/testing/functional_test/${project.timestamp}

wandb_mode: online 
dataset_testing_type: full
epochs: 3
plotting: True
time_analysis: True
num_workers: 7

# evaluate data group metric settings
sample_size: False
n_samples: False
batch_size: 7000

# OBSOLETE
energy_distance:
  K_cross: ${evaluate.energy_distance_standard.K_cross}
  K_within: ${evaluate.energy_distance_standard.K_within}
  batch_size: ${evaluate.energy_distance_standard.batch_size}
  num_permutations: ${evaluate.energy_distance_standard.num_permutations}