# None: no testing, run script as normal 

test_name: none

hydra:
  run:
    dir: ${hydra:runtime.cwd}/logs/${project.project}/${project.task}/${project.name}_${project.timestamp}
  sweep:
    dir: logs/${project.project}/${project.task}/${project.name}_${project.timestamp}


wandb_mode: online 
dataset_testing_type: full
epochs: ${max_epochs}
plotting: False
time_analysis: False
num_workers: 6
timeout_min: 1440
mem_gb: 64

# evaluate data group metric settings
sample_size: 20000
n_samples: False
batch_size: 7000


# OBSOLETE
energy_distance:
  K_cross: ${evaluate.energy_distance_standard.K_cross}
  K_within: ${evaluate.energy_distance_standard.K_within}
  batch_size: ${evaluate.energy_distance_standard.batch_size}
  num_permutations: ${evaluate.energy_distance_standard.num_permutations}