# None: no testing, run script as normal 

test_name: none

hydra:
  run:
    dir: ${hydra:runtime.cwd}/logs/${project.project}/${project.task}/${project.name}_${project.timestamp}
  sweep:
    dir: logs/${project.project}/${project.task}/${project.name}_${project.timestamp}


wandb_mode: online 
dataset_testing_type: full
epochs: ${epochs}
plotting: False
timings: False