# Quick tests: mostly for debugging purposes

test_name: quick_test

hydra:
  run:
    dir: ${hydra:runtime.cwd}/logs/${project.project}/${project.task}/testing/quick_test/${project.timestamp}
  sweep:
    dir: logs/${project.project}/${project.task}/testing/quick_test/${project.timestamp}



wandb_mode: disabled 
dataset_testing_type: quick
epochs: 2
plotting: False
time_analysis: False
num_workers: 1
timeout_min: 60
mem_gb: 32
checkpoint_folder_path: ''


# evaluate data group metric settings
sample_size: False
n_samples: False
batch_size: False

# OBSOLETE
energy_distance:
  K_cross: ${evaluate.energy_distance_test.K_cross}
  K_within: ${evaluate.energy_distance_test.K_within}
  batch_size: ${evaluate.energy_distance_test.batch_size}
  num_permutations: ${evaluate.energy_distance_test.num_permutations}