
defaults:
  - _self_
  - project: config
  - wandb/wkey: wkey
  - dataset: sub_sampled_low_res
  - dataset/general_dataset_config: general_dataset_config
  - evaluate: evaluate_metrics
  - hydra: default
  - testing: qt
  - override hydra/launcher: slurm

multirun_dir_name: eval_data_groups

chunk_size: 1000

evaluation_options: 
  - energy_distance
  # - vis_univariates

energy_distance:
  K_cross: ${testing.energy_distance.K_cross} 
  K_within: ${testing.energy_distance.K_within} 
  batch_size: ${testing.energy_distance.batch_size} 
  num_permutations: ${testing.energy_distance.num_permutations} 

vis_univariates: # Univariate distributions for visualisation
  sample_size: 100000
  variables:
    - near_surface_air_temperature
    - near_surface_specific_humidity
