
defaults:
  - _self_
  - project: config
  - wandb/wkey: wkey
  - dataset: climsim_from_raw
  - model: mlp
  - dataset/general_dataset_config: general_dataset_config
  - evaluate: evaluate_metrics
  - hydra: default
  - testing: qt
  - override hydra/launcher: slurm_gpu

multirun_dir_name: ${evaluation_options[0]}_${metric_name}  #eval_data_groups

evaluation_options: 
  - multivariate
  - marginals
  # - vis_marginals
  
metric_name: energy_distance #kl_divergence #

permutation_test: False # whether to perform permutation test for statistical significance, if False, just computes metric once, if value > 1, permutation test is performed


target_group: 0 # which data group to use as target when computing multivariate metrics, ignored for marginals

vis_marginals: # marginal distributions for visualisation
  sample_size: 1000000
  variables:
    # - near_surface_air_temperature
    # - near_surface_specific_humidity
    - top_3_levels_specific_humidity
  groups_to_plot:
    - 0
    - 6



energy_distance_results_path: '/home/users/bradlesc/projects/ClimSim/logs/p2.1.3/1/testing/functional_test/2025-10-29-17-26-13/eval_data_groups/energy_distance.json'