# General training configuration that is used to train a selected model (with other selected parameters e.g sweep options)

defaults:
  - _self_
  - project: config
  - wandb/wkey: wkey
  - models: models
  - hydra: default
  - testing: none
  - override hydra/launcher: slurm



model_name: mlp
multirun_dir_name: ${model_name}

