# General training configuration that is used to train a selected model (with other selected parameters e.g sweep options)

defaults:
  - _self_
  - project: config
  - wandb/wkey: wkey
  - model: mlp #vib_unet_spatial #yus_mlp
  - dataset: climsim_from_npy_non_stacked #climsim_from_raw #sub_sampled_low_res
  - dataset/general_dataset_config: general_dataset_config
  - hydra: default
  - testing: qt
  - override hydra/launcher: slurm_gpu

# Naming 
multirun_dir_name: ${model.name}_group_${dataset.group_by_months.target_group}_beta_${model.single_run_configuration.beta} #_lr_${model.single_run_configuration.lr}

target_group: MAM #None

# Training parameters
max_epochs: 10

# Sweep options 
sweep: False

# Multi seed options
train_seeds: [0,1,2,3,4,5,6,7,8,9]