# General training configuration that is used to train a selected model (with other selected parameters e.g sweep options)

defaults:
  - _self_
  - project: config
  - wandb/wkey: wkey
  - model: mlp
  - dataset: sub_sampled_low_res
  - hydra: default
  - testing: qt
  - override hydra/launcher: slurm



multirun_dir_name: ${model.name}

max_epochs: 2000