# General training configuration that is used to train a selected model (with other selected parameters e.g sweep options)

defaults:
  - _self_
  - project: config
  - wandb/wkey: wkey
  - model: mlp
  - dataset: sub_sampled_low_res
  - dataset/general_dataset_config: general_dataset_config
  - hydra: default
  - testing: qt
  - override hydra/launcher: slurm

# Naming 
multirun_dir_name: ${model.name}

# Training parameters
max_epochs: 2000

# Sweep options 
sweep: false