project: p2.1.3

task: '3'
name: dataset_evaluation_pipeline
timestamp: ${now:%Y-%m-%d-%H-%M-%S}

seed: 0 # High level seed for general code reproducibility, this will not be used for multiseed runs or sweeps