project: p2.1.3

task: '10'
name: data_process_and_save
timestamp: ${now:%Y-%m-%d-%H-%M-%S}

seed: 0 # High level seed for general code reproducibility, this will not be used for multiseed runs or sweeps