dataset_name: 'climsim_from_raw'

input_dim: 124
output_dim: 128
base_folder_path: '/gws/nopw/j04/iecdt/bstanleyclamp/ClimSim_lowres/train/'
path_to_grid_info: '/home/users/bradlesc/projects/ClimSim/grid_info/ClimSim_low-res_grid-info.nc'

# base_folder_path: '/gws/nopw/j04/iecdt/bstanleyclamp/subsampled_low_res_reduced_for_testing/ClimSim_low-res/train/'

output_scale_file_path: '/home/users/bradlesc/projects/ClimSim/preprocessing/normalizations/outputs/output_scale.nc'
target_years: ['0001','0002','0003','0004','0005','0006','0007','0008','0009']
target_months: ['02'] # Only used if group_method is false

v1_inputs: ['state_t','state_q0001','state_ps','pbuf_SOLIN','pbuf_LHFLX','pbuf_SHFLX']
v1_targets: ['ptend_t','ptend_q0001','cam_out_NETSW','cam_out_FLWDS','cam_out_PRECSC','cam_out_PRECC','cam_out_SOLS','cam_out_SOLL','cam_out_SOLSD', "cam_out_SOLLD"]

dataset_testing_sample_rates:
  unit_test: 1
  quick: 1000
  reduced: 100
  full: 7

# Grouping Settings for splitting into different subgroups to achieve distribution shifts to test generalisation capabilities
group_method: group_by_months # Whether to select a year of data to train on, if not false should be the year [0, 6] to select


group_by_months:
  num_groups: 3 #(02, 03, 04)
  target_group: False
  groups: 
    - ['12', '01', '02']
    - ['03', '04', '05']
    - ['06', '07', '08']
  test_group: ['09', '10', '11']
  val_group: ['09', '10', '11'] # Currently val and test are the same, but could be changed later

remove_high_altitude_specific_humidity_levels: 15
