name: publish-website

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      environment_name: climsim-docs-env
      path_to_notebooks: 'website'

  deploy:
    needs: build
    #Trying this out to see if the auth problem is fixed
    uses: ./.github/workflows/deploy-book.yaml #hack until https://github.com/ProjectPythia/cookbook-actions/pull/45 is merged. 
    # uses: ProjectPythia/cookbook-actions/.github/workflows/deploy-book.yaml@main
    with:
      publish_dir: "website/_build/html"
